[platformio]
default_envs = mqtt

[env:mqtt]
platform = espressif8266@4.2.1
board = esp01_1m
framework = arduino
upload_speed = 115200
upload_resetmethod = nodemcu
extra_scripts = pre:tools/select_config.py
lib_deps =
    adafruit/DHT sensor library@1.4.7
    adafruit/Adafruit Unified Sensor@1.1.15
    256dpi/MQTT@2.5.3
